# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(100, 10, 300, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setGeometry(QtCore.QRect(20, 60, 300, 21))
        self.lbl_status.setObjectName("lbl_status")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setGeometry(QtCore.QRect(360, 50, 111, 31))
        self.btn_connect.setObjectName("btn_connect")
        self.txt_chat_history = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_chat_history.setGeometry(QtCore.QRect(20, 100, 451, 300))
        self.txt_chat_history.setReadOnly(True)
        self.txt_chat_history.setObjectName("txt_chat_history")
        self.txt_message = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_message.setGeometry(QtCore.QRect(20, 420, 351, 31))
        self.txt_message.setObjectName("txt_message")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(390, 420, 81, 31))
        self.btn_send.setEnabled(False)
        self.btn_send.setObjectName("btn_send")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Secure Chat Client"))
        self.lbl_title.setText(_translate("MainWindow", "AES_RSA CHAT"))
        self.lbl_status.setText(_translate("MainWindow", "Trạng thái: Chưa kết nối"))
        self.btn_connect.setText(_translate("MainWindow", "Kết nối Server"))
        self.txt_message.setPlaceholderText(_translate("MainWindow", "Nhập tin nhắn..."))
        self.btn_send.setText(_translate("MainWindow", "Gửi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
