# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 265)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 10, 61, 16))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.btn_generate_keys = QtWidgets.QPushButton(Dialog)
        self.btn_generate_keys.setGeometry(QtCore.QRect(270, 10, 81, 23))
        self.btn_generate_keys.setObjectName("btn_generate_keys")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 51, 16))
        self.label_3.setObjectName("label_3")
        self.txt_information = QtWidgets.QTextEdit(Dialog)
        self.txt_information.setGeometry(QtCore.QRect(100, 40, 331, 71))
        self.txt_information.setObjectName("txt_information")
        self.txt_signature = QtWidgets.QTextEdit(Dialog)
        self.txt_signature.setGeometry(QtCore.QRect(100, 120, 331, 71))
        self.txt_signature.setObjectName("txt_signature")
        self.btn_sign = QtWidgets.QPushButton(Dialog)
        self.btn_sign.setGeometry(QtCore.QRect(100, 200, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(Dialog)
        self.btn_verify.setGeometry(QtCore.QRect(350, 200, 75, 23))
        self.btn_verify.setObjectName("btn_verify")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ECC CIPHER"))
        self.btn_generate_keys.setText(_translate("Dialog", "Generate Keys"))
        self.label_2.setText(_translate("Dialog", "Information:"))
        self.label_3.setText(_translate("Dialog", "Signature:"))
        self.btn_sign.setText(_translate("Dialog", "Sign"))
        self.btn_verify.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
